            - name: Build and Push Docker Image to Docker Hub
  # You may pin to the exact commit or the version.
  uses: FireWork-Production-Private-Ltd/docker-repos@477664b99b7f42135de2f251053007d947f31c44
name: Build and Push Docker Image to Docker Hub

on: push
jobs:
  push_to_registry:
    name: push docker image to hub
    runs-on: ubuntu-latest
    steps:
      - name: check repository
        uses: actions/checkout@v4

      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: build and push docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: DockerFileFolder/
          push: true
          tags: black1512/demo1:latest
