name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build Dockerfile and push image # userで外部ファイル or 定義済みの処理を実行できる。ここではリポジトリのcheckout
      run: |
        IMAGE_NAME=test_container:${GITHUB_REF#refs/heads/} # docer imageの名前とそのタグ、${GITHUB_REF#refs/heads/}でブランチ名を取得している
        docker build ./app --tag ghcr.io/${GITHUB_REPOSITORY}/${IMAGE_NAME}
        docker login --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }}
#       docker login ghcr.io --username ootanimakoto --password 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
        docker push ghcr.io/ootanimakoto/ci/${IMAGE_NAME}
 
